### ISSUE TITLE
Dynamic switching between different IPs not happenning 

### ISSUE THREAD

**Issue by gsssrao** [JdeRobot4Android/AndroidCameraViewer#16] opened 2015-04-15 10:41 UTC
At present, if I have two camera servers on, and I select them from preference menu by changing IPs then the camera view output is not changing. It is still showing the images of the previous IP unless I restart the app.

**Comment by gsssrao** [comment] 2015-04-15 10:44
It seems the problem is from the statement if (cprx == null) only then the cprx was changed. But, even if cprx != null (i.e I have two camera servers on), I should be able to change IPs.

**Comment by ojgarciab** [comment] 2015-04-15 10:50
The problem is not with checked proxy, is with `Ice.Communicator`.

You could do as I do in cameraserver, reload activity, so old communicator is freed (and closed) and new one is created. You could also close it properly and recreate again (assigning cprx to null after it).

Do you want to assign me the issue or you will try to solve it?

**Comment by gsssrao** [comment] 2015-04-15 10:55
Understood. I will try.

**Closed as completed** 2015-04-15 12:00 UTC
Labels: bug
